### PR TITLE
Very fast login!!!

### PR DESCRIPTION
**Pull request by MarvelcoDev**
I have rewrote tokenstuff and made login very fast like in seconds

[makes login very fast(tokenVerify.js)](https://github.com/Lawin0129/LawinServerV2/commit/5c7cb416447f5c31cd2f0d26cb65203a8dc8db38)

[makes login very fast (tokenCreation.js)](https://github.com/Lawin0129/LawinServerV2/commit/195a51b21aeb02ac52f5d9b9f1e5bb315dbd78fb)

### CODE REVIEW

**Comment by MarvelcoOGFN** [comment]
btw i tested this code multiple times so ik it workes (i even have it on my own private backend)

**Comment by AntogamerYT** [comment]
just by sight reading the code, it seems like you just refactored it to make some checks run in different functions

**Comment by MarvelcoOGFN** [comment]
> just by sight reading the code, it seems like you just refactored it to make some checks run in different functions
> 
> it shouldn't change the speed at all

it did make it faster i tried it login takes about 2 min for normal mine takes seconds

**Comment by AntogamerYT** [comment]
> > just by sight reading the code, it seems like you just refactored it to make some checks run in different functions
> > it shouldn't change the speed at all
> 
> it did make it faster i tried it login takes about 2 min for normal mine takes seconds

selfhosted mongo or mongodb atlas? what fortnite version and what platform? (i suppose windows but you might be testing on another platform lol)

**Comment by MarvelcoOGFN** [comment]
> > > just by sight reading the code, it seems like you just refactored it to make some checks run in different functions
> > > it shouldn't change the speed at all
> > 
> > 
> > it did make it faster i tried it login takes about 2 min for normal mine takes seconds
> 
> selfhosted mongo or mongodb atlas? what fortnite version and what platform are you using to test fortnite? (i suppose windows but you might be testing on another platform lol)

win10 s12.41 self mongo and i tested on my friends rdp on mongoatlas all works good and supports any fortnite build

**Pull request closed without merging**
