### PR TITLE
Added some features

### PR DESCRIPTION
**Pull request by optixyt0**
I have added features to the Discord Bot and have modified the locker functions.

### CODE REVIEW

**Comment by optixyt0** [comment]
Do you think this is suitable to merge?

**Comment by optixyt0** [comment]
I've also fixed some severe vulnerabilities for mongoose with the packages

**Comment by secret-pommes** [comment]
bro what is that ☠️

**Comment by optixyt0** [comment]
Wdym?

**Comment by Playeereq** [comment]
💀

**Comment by optixyt0** [comment]
Tbh, I only want the Readme merged

**Comment by optixytv3** [comment]
oh my fucking god this was so skidded :sob:

**Comment by optixytv3** [comment]
i was very stupid in '23

**Pull request closed without merging**
