### PR TITLE
Tg nick patch 1

### PR DESCRIPTION
**Pull request by TGNick**

### CODE REVIEW

**Comment by AntogamerYT** [comment]
what the sigma

**Comment by endlessalpacaYT** [comment]
> what the sigma

BRO CALLS ME A CHILD BUT SAYS SHIT LIKE THAT

**Comment by ojotaa0124** [comment]
wtf is this pull request 😭

**Comment by TGNick** [comment]
Idk tbh

**Comment by TGNick** [comment]
Mb

**Pull request closed without merging**
